= Asciidoctor Documentation Site
// Settings:
:hide-uri-scheme:
// Project URIs:
:url-project: https://asciidoctor.org
:url-site: https://docs.asciidoctor.org
:url-org: https://github.com/asciidoctor
:url-docs-ui: https://github.com/asciidoctor/asciidoctor-docs-ui
// External URIs:
:url-antora: https://antora.org
:url-antora-install: https://docs.antora.org/antora/latest/install/install-antora/
:url-letsencrypt: https://letsencrypt.org
:url-netlify: https://www.netlify.com
:url-netlify-deploys: https://app.netlify.com/sites/asciidoctor-docs/deploys

This repository contains an Antora playbook project for building the documentation site for the BBC BASIC (Z80) Manual for the Agon Light.

== Documentation Structure

The documentation site is built using {url-antora}[Antora].
The content is pulled from the https://github.com/oldpatientsea/agon-bbc-basic-manual[Agon BBC BASIC Manual repository on GitHub].  
This sources is defined in the Antora playbook file, [.path]_antora-playbook.yml_.
Each content source points to a folder in one or more branches that is structured as a documentation component, which Antora consumes.

The UI for the site is hosted in a separate repository, {url-docs-ui}[asciidoctor-docs-ui].

== Quickstart

To generate the Asciidoctor Docs site, you first need to install {url-antora}[Antora].
We recommend installing and running the `antora` command on the playbook file hosted in this repository using `npx`.
npx installs Antora the *antora* package globally into an isolated directory, then runs the corresponding `antora` command.

 $ npx antora antora-playbook.yml

If you are having issues with stale, cached content, pass the --fetch flag to pull the latest.

 $ npx antora --fetch antora-playbook.yml

To learn more, refer to the {url-antora-install}[installation instructions] in the Antora documentation.

The command will generate a site which may be viewed offline.


== Copyright and License

Asciidoctor is copyright (C) 2020-present Dan Allen, Sarah White, and individual contributors to the docs.asciidoctor.org repository.

The source and configuration files in this repository are licensed under the terms of the MIT License.

The build for this documentation site sources content the licence for which is still to be agreed.

Unless otherwise noted, the documentation content is licensed under a https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License] (CC BY 4.0).

Use of the {url-org}[Asciidoctor projects] are granted under the terms of each software project's open source license.

Those licenses include MIT, Apache-2.0, and CC BY 4.0.

